version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: toqa-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - toqa_mongo_data:/data/db

volumes:
  toqa_mongo_data:
