version: '3.8'

services:
  api:
    build: .
    container_name: checkout-orders-payment-api
    restart: unless-stopped
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/checkout_orders_payment
    depends_on:
      - mongo
    volumes:
      - ./logs:/usr/src/app/logs
      - ./uploads:/usr/src/app/uploads

  mongo:
    image: mongo:6
    container_name: checkout-orders-payment-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
