const router = require("express").Router();
const admin = require("../controllers/admin.controller");
const product = require("../controllers/product.controller");
const category = require("../controllers/category.controller");
const variant = require("../controllers/variant.controller");
const coupon = require("../controllers/coupon.controller");
const attribute = require("../controllers/attribute.controller");
const { authenticate } = require("../middlewares/auth.middleware");
const authorize = require("../middlewares/role.middleware");
const validate = require("../middlewares/validate.middleware");
const ROLES = require("../constants/roles");
const { productValidator } = require("../validators/product.validator");
const { categoryValidator } = require("../validators/category.validator");
const { variantValidator, stockValidator } = require("../validators/variant.validator");
const { couponValidator } = require("../validators/coupon.validator");
const { orderStatusValidator, paymentStatusValidator } = require("../validators/order.validator");

router.use(authenticate, authorize(ROLES.ADMIN));
router.get("/dashboard", admin.getDashboard);
router.get("/products", product.list);
router.post("/products", productValidator, validate, product.create);
router.patch("/products/:productId", product.update);
router.delete("/products/:productId", product.remove);
router.patch("/products/:productId/status", product.status);
router.post("/products/:productId/variants", variantValidator, validate, variant.create);
router.patch("/variants/:variantId", variant.update);
router.delete("/variants/:variantId", variant.remove);
router.patch("/variants/:variantId/stock", stockValidator, validate, variant.stock);
router.post("/categories", categoryValidator, validate, category.create);
router.get("/categories", category.list);
router.patch("/categories/:categoryId", category.update);
router.delete("/categories/:categoryId", category.remove);
router.get("/sizes", attribute.list("sizes"));
router.post("/sizes", attribute.create("sizes"));
router.patch("/sizes/:id", attribute.update("sizes"));
router.delete("/sizes/:id", attribute.remove("sizes"));
router.get("/colors", attribute.list("colors"));
router.post("/colors", attribute.create("colors"));
router.patch("/colors/:id", attribute.update("colors"));
router.delete("/colors/:id", attribute.remove("colors"));
router.get("/inventory", variant.inventory);
router.get("/inventory/low-stock", variant.lowStock);
router.get("/orders", admin.listOrders);
router.get("/orders/:orderId", admin.getOrder);
router.patch("/orders/:orderId/status", orderStatusValidator, validate, admin.setOrderStatus);
router.patch("/orders/:orderId/payment-status", paymentStatusValidator, validate, admin.setPaymentStatus);
router.get("/coupons", coupon.list);
router.post("/coupons", couponValidator, validate, coupon.create);
router.patch("/coupons/:couponId", coupon.update);
router.delete("/coupons/:couponId", coupon.remove);
router.get("/users", admin.listUsers);
router.get("/users/:userId", admin.getUser);
router.patch("/users/:userId/status", admin.setUserStatus);
router.get("/reviews", admin.listReviews);
router.delete("/reviews/:reviewId", admin.deleteReview);
module.exports = router;
