const crypto = require('crypto');

/**
 * Simulated Electronic Wallet payment processor.
 * In a real system this would call an external payment gateway
 * (e.g. Fawry, Paymob, Stripe...) via HTTP. It is isolated here so the
 * real integration can be swapped in without touching controllers.
 */
const processWalletPayment = async ({ orderId, amount, walletPhone }) => {
  if (!walletPhone) {
    return {
      success: false,
      status: 'failed',
      reference: null,
      message: 'Wallet phone number is required for electronic wallet payments'
    };
  }

  // Simulate a payment reference generated by the gateway
  const reference = `PAY-${Date.now()}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;

  return {
    success: true,
    status: 'pending', // becomes 'paid' once gateway confirms/webhook fires
    reference,
    message: `Payment of ${amount} initiated for order ${orderId}`
  };
};

module.exports = { processWalletPayment };
