import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, money } from "../api";
import { useAuth } from "../auth";

export default function Account() {
  const {user,setUser}=useAuth(); const [tab,setTab]=useState("orders"); const [orders,setOrders]=useState([]); const [wishlist,setWishlist]=useState([]); const [form,setForm]=useState(user); const [notice,setNotice]=useState("");
  useEffect(()=>{if(tab==="orders")api("/orders").then((d)=>setOrders(d.orders));if(tab==="wishlist")api("/wishlist").then((d)=>setWishlist(d.products||[]));},[tab]);
  const save=async(e)=>{e.preventDefault();const data=await api("/users/me",{method:"PATCH",body:JSON.stringify({name:form.name,phone:form.phone,address:form.address,governorate:form.governorate})});setUser(data);setNotice("Profile saved.");};
  const moveToCart=async(product)=>{const detail=await api(`/products/${product._id}`);const variant=detail.variants.find(item=>item.stock>0);if(!variant)return setNotice("This product is out of stock.");await api("/cart/items",{method:"POST",body:JSON.stringify({variantId:variant._id,quantity:1})});await api(`/wishlist/${product._id}`,{method:"DELETE"});setWishlist(items=>items.filter(item=>item._id!==product._id));setNotice("Moved to your bag.");};
  return <section className="account-page"><aside><p className="eyebrow">Your ToQa</p><h2>{user.name}</h2>{["orders","wishlist","profile"].map((item)=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</aside><div className="account-content">{notice&&<p className="notice">{notice}</p>}{tab==="orders"&&<><h1>Order history</h1>{orders.length?orders.map((order)=><Link className="order-card" to={`/orders/${order._id}`} key={order._id}><div><strong>{order.orderNumber}</strong><p>{new Date(order.createdAt).toLocaleDateString()}</p></div><div><span className="status">{order.orderStatus}</span><strong>{money(order.total)}</strong></div></Link>):<div className="empty-card">No orders yet.</div>}</>}{tab==="wishlist"&&<><h1>Wishlist</h1><div className="mini-grid">{wishlist.map((product)=><article key={product._id}><Link to={`/products/${product.slug}`}><img src={product.images?.[0]||"https://placehold.co/400x500"}/><h3>{product.name}</h3><p>{money(product.basePrice)}</p></Link><button className="button outline full" onClick={()=>moveToCart(product)}>Move to bag</button></article>)}</div></>}{tab==="profile"&&<form className="form-card flat" onSubmit={save}><h1>Your details</h1>{["name","phone","address","governorate"].map((key)=><label className="field" key={key}><span>{key}</span><input value={form[key]||""} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></label>)}<button className="button dark">Save changes</button></form>}</div></section>;
}
